apiVersion: v1
kind: Service
metadata:
  name: hotelbooking
  labels:
    name: hotelbooking
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: hotelbooking
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelbooking
spec:
  selector:
    matchLabels:
      app: hotelbooking
  replicas: 1
  template:
    metadata:
      labels:
        app: hotelbooking
    spec:
      containers:
        - name: hotelbooking
          image: hotelbooking:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password