--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Homebrew)
-- Dumped by pg_dump version 16.4

-- Started on 2024-12-06 17:10:56 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 25277)
-- Name: authorization_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authorization_token (
    id bigint NOT NULL,
    creation_time timestamp(6) with time zone NOT NULL,
    token character varying(255) NOT NULL,
    client_id bigint NOT NULL
);


ALTER TABLE public.authorization_token OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 25276)
-- Name: authorization_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authorization_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authorization_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 25283)
-- Name: base_room_configuration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_room_configuration (
    id bigint NOT NULL,
    area integer NOT NULL,
    base_coast integer NOT NULL,
    card_description character varying(255) NOT NULL,
    full_description character varying(800) NOT NULL,
    max_guests integer NOT NULL,
    name character varying(255) NOT NULL,
    rooms integer NOT NULL
);


ALTER TABLE public.base_room_configuration OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 25282)
-- Name: base_room_configuration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_room_configuration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_room_configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 25291)
-- Name: booking_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.booking_record (
    id bigint NOT NULL,
    end_date date,
    guests_count integer NOT NULL,
    start_date date,
    total_coast integer NOT NULL,
    client_id bigint NOT NULL,
    room_id bigint NOT NULL,
    CONSTRAINT booking_record_total_coast_check CHECK ((total_coast > 0))
);


ALTER TABLE public.booking_record OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 25290)
-- Name: booking_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.booking_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 25298)
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    id bigint NOT NULL,
    name character varying(255),
    phone_number character varying(255) NOT NULL,
    roles character varying(255) NOT NULL
);


ALTER TABLE public.client OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 25297)
-- Name: client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 25306)
-- Name: extended_room_configuration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.extended_room_configuration (
    id bigint NOT NULL,
    booking_name character varying(255) NOT NULL,
    is_on_main boolean NOT NULL,
    base_room_configuration_id bigint NOT NULL
);


ALTER TABLE public.extended_room_configuration OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 25305)
-- Name: extended_room_configuration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.extended_room_configuration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.extended_room_configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 25312)
-- Name: price_schedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.price_schedule (
    id bigint NOT NULL,
    coast integer NOT NULL,
    date date,
    base_room_configuration_id bigint NOT NULL
);


ALTER TABLE public.price_schedule OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 25311)
-- Name: price_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.price_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 25318)
-- Name: room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.room (
    id bigint NOT NULL,
    extended_room_configuration_id bigint NOT NULL
);


ALTER TABLE public.room OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 25317)
-- Name: room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 25324)
-- Name: room_photo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.room_photo (
    id bigint NOT NULL,
    output_order integer NOT NULL,
    photo_path character varying(255) NOT NULL,
    extended_room_configuration_id bigint NOT NULL
);


ALTER TABLE public.room_photo OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 25323)
-- Name: room_photo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.room_photo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_photo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3548 (class 2606 OID 25281)
-- Name: authorization_token authorization_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authorization_token
    ADD CONSTRAINT authorization_token_pkey PRIMARY KEY (id);


--
-- TOC entry 3554 (class 2606 OID 25289)
-- Name: base_room_configuration base_room_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_room_configuration
    ADD CONSTRAINT base_room_configuration_pkey PRIMARY KEY (id);


--
-- TOC entry 3558 (class 2606 OID 25296)
-- Name: booking_record booking_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking_record
    ADD CONSTRAINT booking_record_pkey PRIMARY KEY (id);


--
-- TOC entry 3560 (class 2606 OID 25304)
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- TOC entry 3564 (class 2606 OID 25310)
-- Name: extended_room_configuration extended_room_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.extended_room_configuration
    ADD CONSTRAINT extended_room_configuration_pkey PRIMARY KEY (id);


--
-- TOC entry 3568 (class 2606 OID 25316)
-- Name: price_schedule price_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.price_schedule
    ADD CONSTRAINT price_schedule_pkey PRIMARY KEY (id);


--
-- TOC entry 3572 (class 2606 OID 25328)
-- Name: room_photo room_photo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room_photo
    ADD CONSTRAINT room_photo_pkey PRIMARY KEY (id);


--
-- TOC entry 3570 (class 2606 OID 25322)
-- Name: room room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT room_pkey PRIMARY KEY (id);


--
-- TOC entry 3550 (class 2606 OID 25330)
-- Name: authorization_token uk4ug8fvmuiwkxarwiq7tyn82dg; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authorization_token
    ADD CONSTRAINT uk4ug8fvmuiwkxarwiq7tyn82dg UNIQUE (token);


--
-- TOC entry 3566 (class 2606 OID 25338)
-- Name: extended_room_configuration ukct33wfpcx4sv94cst2gyacfg0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.extended_room_configuration
    ADD CONSTRAINT ukct33wfpcx4sv94cst2gyacfg0 UNIQUE (booking_name);


--
-- TOC entry 3562 (class 2606 OID 25336)
-- Name: client ukjgbii7eaw72fc9llajcdeyjb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT ukjgbii7eaw72fc9llajcdeyjb UNIQUE (phone_number);


--
-- TOC entry 3556 (class 2606 OID 25334)
-- Name: base_room_configuration ukp3oscycw1ao41mg6pvxx5wbgj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_room_configuration
    ADD CONSTRAINT ukp3oscycw1ao41mg6pvxx5wbgj UNIQUE (name);


--
-- TOC entry 3552 (class 2606 OID 25332)
-- Name: authorization_token ukr3lbbtp3e25chqi9gjdyjxd2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authorization_token
    ADD CONSTRAINT ukr3lbbtp3e25chqi9gjdyjxd2 UNIQUE (client_id);


--
-- TOC entry 3578 (class 2606 OID 25364)
-- Name: room fk6pxhvhgubotgsbmak8hk2narx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT fk6pxhvhgubotgsbmak8hk2narx FOREIGN KEY (extended_room_configuration_id) REFERENCES public.extended_room_configuration(id);


--
-- TOC entry 3576 (class 2606 OID 25354)
-- Name: extended_room_configuration fkcfoqg0uf37ghdxpvx7cbbejcu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.extended_room_configuration
    ADD CONSTRAINT fkcfoqg0uf37ghdxpvx7cbbejcu FOREIGN KEY (base_room_configuration_id) REFERENCES public.base_room_configuration(id);


--
-- TOC entry 3577 (class 2606 OID 25359)
-- Name: price_schedule fkcvklhgjei9t5kfcrj94dpqtf7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.price_schedule
    ADD CONSTRAINT fkcvklhgjei9t5kfcrj94dpqtf7 FOREIGN KEY (base_room_configuration_id) REFERENCES public.base_room_configuration(id);


--
-- TOC entry 3573 (class 2606 OID 25339)
-- Name: authorization_token fkd7l7eaaym2ndmiitgltx37l2m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authorization_token
    ADD CONSTRAINT fkd7l7eaaym2ndmiitgltx37l2m FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- TOC entry 3574 (class 2606 OID 25349)
-- Name: booking_record fkh87o8f62v3tx1whf8r0m44m7o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking_record
    ADD CONSTRAINT fkh87o8f62v3tx1whf8r0m44m7o FOREIGN KEY (room_id) REFERENCES public.room(id);


--
-- TOC entry 3575 (class 2606 OID 25344)
-- Name: booking_record fkkcfg2e0jeg4c0485k4ax2o1wv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking_record
    ADD CONSTRAINT fkkcfg2e0jeg4c0485k4ax2o1wv FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- TOC entry 3579 (class 2606 OID 25369)
-- Name: room_photo fkoi3oxmmae8ukyjbf62tbb09iw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room_photo
    ADD CONSTRAINT fkoi3oxmmae8ukyjbf62tbb09iw FOREIGN KEY (extended_room_configuration_id) REFERENCES public.extended_room_configuration(id);


-- Completed on 2024-12-06 17:10:56 MSK

--
-- PostgreSQL database dump complete
--

